# version: '3.3'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile  # Specify the Dockerfile if it's not named 'Dockerfile'
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/app  # Mounts the current directory into the container

version: '3.8'

services:
  vite_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    restart: unless-stopped
