version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the Dockerfile if it's not named 'Dockerfile'
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mounts the current directory into the container
