const CATALOG_API_PORT = import.meta.env.VITE_CATALOG_API_PORT;
const AGENT_PORT = import.meta.env.VITE_AGENT_PORT;
const AUDIT_PORT = import.meta.env.VITE_AUDIT_PORT;
const MONITOR_PORT = import.meta.env.VITE_MONITOR_PORT;
const KEYCLOAK_API_PORT = import.meta.env.VITE_KEYCLOAK_API_PORT;
const DECRYPTION_KEY = import.meta.env.VITE_DECRYPTION_KEY;
const KEYCLOAK_REDIRECT_URI = import.meta.env.VITE_KEYCLOAK_REDIRECT_URI
const KEYCLOAK_URL = import.meta.env.VITE_KEYCLOAK_URL;
const KEYCLOAK_REALM = import.meta.env.VITE_KEYCLOAK_REALM;
const KEYCLOAK_CLIENT_ID = import.meta.env.VITE_KEYCLOAK_CLIENT_ID;
const AUTO_SAVE_TIME = import.meta.env.VITE_AUTO_SAVE_TIME;
const API_DOMAIN = import.meta.env.VITE_API_DOMAIN;
const API_PREFIX_URL = import.meta.env.VITE_API_PREFIX_URL;

export { CATALOG_API_PORT, AGENT_PORT, AUDIT_PORT, MONITOR_PORT, 
    KEYCLOAK_API_PORT, DECRYPTION_KEY, KEYCLOAK_REDIRECT_URI,
    KEYCLOAK_URL, KEYCLOAK_REALM, KEYCLOAK_CLIENT_ID,
    AUTO_SAVE_TIME, API_DOMAIN, API_PREFIX_URL
};
